### PR TITLE
feat(TicketsAgent): export tickets list in excel,csv format

### PR DESCRIPTION
**Pull request by sumitbhanushali**

### CODE REVIEW

**Comment by RitvikSardana** [comment]
@sumitbhanushali please add some description and screenshots

**Comment by RitvikSardana** [comment]
regardless of the rows selected the export is for all the records, so the checkbox does not have any meaning.

It exports all the tickets out of the box. Even if we uncheck the Checkbox. @sumitbhanushali

**Comment by sumitbhanushali** [comment]
> regardless of the rows selected the export is for all the records, so the checkbox does not have any meaning.
> 
> It exports all the tickets out of the box. Even if we uncheck the Checkbox. @sumitbhanushali 
> 
> 
> 

It doesn't work with check boxes currently...it exports what is on current page or all...

That is what checkbox is used for

**Comment by RitvikSardana** [comment]
It it not intuitive enough what rows will be exported, it should be done for the selected rows.

**Pull request merged**
