### PR TITLE
fix: update sla based on condition

### PR DESCRIPTION
**Pull request by fadilsid**
Resolves sla not updating based on condition in tickets.

### CODE REVIEW

**Comment by fadilsid** [comment]
@netchampfaris please review.

**Review by netchampfaris — COMMENTED** [review]
Now that I think about it, the `or_filters` was there in case no SLA was found and it should keep the SLA that was applied. So, the logic should be "find an applicable SLA, if it is not found then return the SLA that is already applied"

**Comment by harshit-30** [comment]
@fadilsid did you review what @netchampfaris has mentioned here?

**Comment by fadilsid** [comment]
> @fadilsid did you review what @netchampfaris has mentioned here?

yes, if not sla is found for a ticket it applies the previously applied sla of the ticket.

**Pull request merged**
