### PR TITLE
feat: update status after replying to a ticket

### LINKED ISSUE #462: feat: update status while sending
Add an ability to mark it as Replied, Resolved, or Closed while sending a message. 
the options should be: 
- Send
- Send and set as Replied 
- Send and set as Resolved 
- Send and set as Closed

`Send should be the default option`

it should look something like this: 
image

### PR DESCRIPTION
**Pull request by fadilsid**
Resolves #462 
1. Ability to mark ticket status as Replied, Resolved, or Closed while sending a message.
Screenshot from 2023-01-13 15-27-09

### CODE REVIEW

**Comment by harshit-30** [comment]
@fadilsid the dropdown should open above the button. 

Cc. @esafwan did you review this?

**Comment by harshit-30** [comment]
@fadilsid any updates on this?

**Comment by harshit-30** [comment]
@fadilsid any updates here?

**Comment by ssiyad** [comment]
closing in favour of https://github.com/frappe/helpdesk/pull/1044

**Pull request closed without merging**
