### PR TITLE
fix: empty responses should not be allowed.

### PR DESCRIPTION
**Pull request by kurogeek**
Responses (Replies/Comments) should not be empty.

I don't know if this is the right way to do it. If there's another way to do this, please advice.

### CODE REVIEW

**Comment by ssiyad** [comment]
This looks good. However, there is a `validate` function in frappe-ui intended for this. Check https://frappeui.com/resources/resource.html

**Comment by kurogeek** [comment]
Got it, I'll fix it.

**Comment by kurogeek** [comment]
@ssiyad Just fixed it, please review and let me know if there is any thing wrong.

Thank you for your guide BTW.

**Comment by ssiyad** [comment]
@kurogeek Hey, are you working on this? Can you check the review and make necessary changes?

**Comment by kurogeek** [comment]
Yes I am, let me try to fix it.

**Comment by kurogeek** [comment]
Seems like the error is about a commit title violate commitlints. I'm going to close this one and recreate a new PR. So that I can properly add commit message.

**Pull request closed without merging**
