### PR TITLE
fix: list agent and contact

### LINKED ISSUE #1284: Agent and Contact list view not able to shown
1. Agent and Contact list not able to view

pymysql.err.OperationalError: (1054, "Unknown column 'user.full_name' in 'field list'")

image

### PR DESCRIPTION
**Pull request by kurogeek**
This is the best I can do to fix #1284

### CODE REVIEW

**Review by singhranbir — COMMENTED** [review]
looks all colkey is corrected.

**Comment by ssiyad** [comment]
@kurogeek can you please explain the root cause? Also, does this happen in both v14 and v15?

**Comment by nextchamp-saqib** [comment]
Fixed: 24937ad

**Comment by kurogeek** [comment]
@nextchamp-saqib This is not fixed. Since there are incoming issues about this problem. #1413 #1418

**Pull request closed without merging**
