### PR TITLE
customer listing in ticket activity

### PR DESCRIPTION
**Pull request by NihalRoshanCK**
customer listing fixed at the ticket activity right sidebar
helpdesk_bug

### CODE REVIEW

**Comment by Nihalroshan55** [comment]
when we create a new ticket from helpdesk we can't add customer reference after creating that we have a view that shows all the ticket details in its sidebar there are details including customer and all if there is no customer (in case we create it from helpdesk ) 
from there customer listing is not working

**Comment by rmehta** [comment]
can you send a clear video?

**Comment by Nihalroshan55** [comment]
https://github.com/user-attachments/assets/cf27f31c-677e-4699-a403-35236426cec1

**Comment by sumitbhanushali** [comment]
@Nihalroshan55 in your change, you are fetching data from Customer in agentstore? was this by mistake?

Also, Customers are fetched based on Contact -> Customer mapping. If a contact doesn't have customer mapped, It shows blank. This thing needs better UX but no change in functionality afaik

**Comment by Nihalroshan55** [comment]
yes, it's done by mistake changed it back @sumitbhanushali

**Comment by sumitbhanushali** [comment]
@Nihalroshan55 checkout `get_customer` api at helpdesk/utils.py.

basically, it fetches customer from given Contact. This contact must have mapping in Contact doctype in links child table

**Comment by Nihalroshan55** [comment]
as in our use case,  we received a call for a product bug,  which we are trying to manually create a ticket on behalf of customer. Here we would like to create a customer manually or sync from our customer list. (this is a non frappe external use case)

**Comment by RitvikSardana** [comment]
fixed via: https://github.com/frappe/helpdesk/pull/2063/commits/f82fdaa03cd5954cf66c2a15357c23f00a18fd10

**Pull request closed without merging**
